### ISSUE TITLE
["invalid input.  Request not processed. "] error on curl command

### ISSUE THREAD

**Issue by chappg** [aws-samples/s3-select-phonebook-search#4]
I've followed the sample instructions and everything worked OK until executing the curl command verification step.

curl -d '{"name":"Jane"}' -X POST https://s7ie578tq4.execute-api.us-west-2.amazonaws.com/Prod/s3-select-demo
["invalid input.  Request not processed. "]

Verbose output follows:

curl -d '{"name":"Jane"}' -X POST https://s7ie578tq4.execute-api.us-west-2.amazonaws.com/Prod/s3-select-demo --verbose
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 54.230.126.129...
* TCP_NODELAY set
* Connected to s7ie578tq4.execute-api.us-west-2.amazonaws.com (54.230.126.129) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS Unknown, Certificate Status (22):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS Unknown, Certificate Status (22):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS Unknown, Certificate Status (22):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS Unknown, Certificate Status (22):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS change cipher, Client hello (1):
* (304) (OUT), TLS Unknown, Certificate Status (22):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using unknown / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.execute-api.us-west-2.amazonaws.com
*  start date: Oct 24 00:00:00 2020 GMT
*  expire date: Nov 23 23:59:59 2021 GMT
*  subjectAltName: host "s7ie578tq4.execute-api.us-west-2.amazonaws.com" matched cert's "*.execute-api.us-west-2.amazonaws.com"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* (304) (OUT), TLS Unknown, Unknown (23):
* (304) (OUT), TLS Unknown, Unknown (23):
* (304) (OUT), TLS Unknown, Unknown (23):
* Using Stream ID: 1 (easy handle 0x7fffd838e580)
* (304) (OUT), TLS Unknown, Unknown (23):
> POST /Prod/s3-select-demo HTTP/2
> Host: s7ie578tq4.execute-api.us-west-2.amazonaws.com
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Length: 15
> Content-Type: application/x-www-form-urlencoded
>
* (304) (OUT), TLS Unknown, Unknown (23):
* We are completely uploaded and fine
* (304) (IN), TLS Unknown, Unknown (23):
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
* (304) (OUT), TLS Unknown, Unknown (23):
* (304) (IN), TLS Unknown, Unknown (23):
* (304) (IN), TLS Unknown, Unknown (23):
< HTTP/2 200
< content-type: application/json
< content-length: 43
< date: Fri, 05 Feb 2021 19:41:10 GMT
< x-amzn-requestid: 32cb354a-d67a-4b56-b127-4ced637c09f8
< x-amz-apigw-id: aSXVcGjzvHcFUoQ=
< x-powered-by: AWS API Gateway & Lambda Serverless
< x-amzn-trace-id: Root=1-601d9f55-14b025925b1f8fd112b1953c;Sampled=0
< x-cache: Miss from cloudfront
< via: 1.1 802eebfb6e9ab6bda66a7156bc7add93.cloudfront.net (CloudFront)
< x-amz-cf-pop: HIO50-C2
< x-amz-cf-id: oyhEXHPyEvMUq4M-81YI_uoZRj_E-iSgAjffJu4R28fQJ1RpisqT8Q==
<
* (304) (IN), TLS Unknown, Unknown (23):
* Connection #0 to host s7ie578tq4.execute-api.us-west-2.amazonaws.com left intact
["invalid input.  Request not processed. "]

**Comment by chappg** [comment]
Resolved issue: root cause is sample_data.csv must be in the s3 bucket root, not in the directory structure of the git package (tst/resources/...).

**Comment by davidmgre** [comment]
HI @chappg, Thank you for your feedback. I have updated the readme and specified the sample_data.csv file needs to be uploaded to the top level / root of S3.
